stages:
    - build
    - package
    - deploy

build:
    image: node:16
    stage: build
    cache:
        paths:
            - node_modules
    only:
        - develop
    tags:
        - devland
    script:
        - yarn install --network-timeout 1000000000
        - CI=false yarn build
    artifacts:
        expire_in: 1 week
        paths:
            - build

package:
    image: docker:20.10.13
    stage: package
    only:
        - develop
    tags:
        - devland
    before_script:
        - docker info
        - echo $CI_REGISTERY_PASSWORD | docker login  $CI_REGISTERY_URL --username $CI_REGISTERY_USER  --password-stdin
    script:
        - docker build --file Dockerfile -t $CI_REGISTERY_IMAGE .
        - docker push $CI_REGISTERY_IMAGE

deploy:
    image: ibmcom/curl:4.2.0-f4
    stage: deploy
    only:
        - develop
    script:
        - curl -X POST $CI_PORTAINER_WEBHOOK
    tags:
        - devland
