import { PushNotification } from '@app/components/modal/PushNotification';
export default {
  auth: '/api/TokenAuth',
  users: '/api/services/app/User',
  services: '/api/services/app/Service',
  subServices: '/api/services/app/SubService',
  tools: '/api/services/app/tool',
  sourceType: '/api/services/app/SourceType',
  countries: '/api/services/app/Country',
  cities: '/api/services/app/City',
  regions: '/api/services/app/Region',
  contactUs: '/api/services/app/ContactUs',
  companies: '/api/services/app/Company',
  attributeForSourceType: '/api/services/app/AttributeForSourceType',
  allAttributeChoices: '/api/services/app/AttributeChoice',
  partner: '/api/services/app/Partner',
  Mediator: '/api/services/app/Mediator',
  roles: '/api/services/app/Role',
  requests: '/api/services/app/RequestForQuotation',
  branches: '/api/services/app/CompanyBranch',
  pushNotifications: '/api/services/app/PushNotification',
  privacyPolicy: '/api/services/app/PrivacyPolicy',
  term: '/api/services/app/Term',
  ask: '/api/services/app/User',
  frequentlyQuestions: '/api/services/app/FrequentlyQuestion',
  offers: '/api/services/app/Offer',
  points: '/api/services/app/Point',
  rejectReason: '/api/services/app/RejectReason',
  drafts: '/api/services/app/Draft',
  attachment: '/api/services/app/Attachment',
};
