export default {
  auth: '/api/TokenAuth',
  users: '/api/services/app/User',
  services: '/api/services/app/Service',
  subServices: '/api/services/app/SubService',
  tools: '/api/services/app/tool',
  sourceType: '/api/services/app/SourceType',
  countries: '/api/services/app/Country',
  cities: '/api/services/app/City',
  regions: '/api/services/app/Region',
  contactUs: '/api/services/app/ContactUs',
  companies: '/api/services/app/Company',
  attributeForSourceType: '/api/services/app/AttributeForSourceType',
  allAttributeChoices: '/api/services/app/AttributeChoice',
  partner: '/api/services/app/Partner',
  Mediator: '/api/services/app/Mediator',
  roles: '/api/services/app/Role',
  requests: '/api/services/app/RequestForQuotations',
};
